### ISSUE TITLE
Segmentation fault in RecSplit

### ISSUE THREAD

**Issue by jnalanko** [vigna/sux#7]
Hello,

I have the following code:

```
#include "sux/function/RecSplit.hpp"

using namespace sux::function;

int main() {
	vector<hash128_t> keys;
	for (int i = 0; i < 10000; i++) {
		keys.push_back(hash128_t(0, i));
	}
	RecSplit<8> RS(keys, 100);
}
```

Compiled with `g++ -std=c++17`, this crashes with a segmentation fault. If the loop goes up to only 1000, it works. Why is that? Thanks.

**Comment by vigna** [comment]
Please read the docs.

/** 128-bit hashes.
 *
 * In the construction of RecSplit, keys are replaced with instances
 * of this class using SpookyHash, first thing.
 * Moreover, it is possible to build and query RecSplit instances using 128-bit
 * random hashes only (mainly for benchmarking purposes).
 */

**Comment by jnalanko** [comment]
Sorry and thank you!
