### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by thedrow** [vigna/sux#9]
I don't understand exactly what do you mean by "Succinct data structures in C/C++" and so will most people.
A short description of the project would help to find it and research about it.

**Comment by vigna** [comment]
Well, if you do not know what succinct data structures are you do not need this library...

**Comment by thedrow** [comment]
But maybe I do need them and I don't know it yet.
Don't assume anything about your users, just explain why your project is useful. These are my two cents.
